build:
  rules:
    - if: '$CI_COMMIT_BRANCH == spa'
  image: docker:19.03.12
  stage: build
  services:
    - docker:19.03.12-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/tstark2/static-server/spa:latest .
    - docker push $CI_REGISTRY/tstark2/static-server/spa:latest
